version: "version"

services:
  db:
    env_file: server/.env
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=msg_clone
      - POSTGRES_USER=${DB_USER}
    restart: always
